#Dockerfile

#FROM nginx 
#COPY . /usr/share/nginx/html

FROM python:3.9

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt
RUN pip install requests
RUN pip install bs4

# copy the content of the local src directory to the working directory
COPY src .

# command to run on container start
CMD [ "python", "./app.py"]

#EXPOSE 8000