#Dockerfile

FROM python:3.9

# Répertoire de travail dans le conteneur
WORKDIR /code

# copier le fichier de dépendances dans le répertoire de travail
COPY requirements.txt .

# installation des dépendances 
RUN pip install -r requirements.txt
RUN pip install requests
RUN pip install bs4

# Copier le contenu du répertoire source dans le répertoire de travail
COPY src .

# Commande à lancer quand le conteneur démarre
CMD [ "python", "./app.py"]
